name: prepare

runs:
  using: "composite"

  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Clippy check
      run: cargo clippy -- -D warnings
