name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Default Rust actions
        uses: ./.github/workflows/rust_reusable

      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN : ${{ secrets.CARGO_REGISTRY_TOKEN  }}
        run: cargo publish --token $CARGO_REGISTRY_TOKEN
