name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare
        uses: djsora/rust_test_repo_dont_use_it_1337/.github/workflows/prepare@main

      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN : ${{ secrets.CARGO_REGISTRY_TOKEN  }}
        run: cargo publish --token $CARGO_REGISTRY_TOKEN
